apiVersion: policies.kyverno.io/v1alpha1
kind: GeneratingPolicy
metadata:
  name: add-ns-resourcequota
  annotations:
    policies.kyverno.io/title: Add ResourceQuota
    policies.kyverno.io/category: Multi-Tenancy, EKS Best Practices
    policies.kyverno.io/subject: ResourceQuota
    policies.kyverno.io/minversion: 1.15.0
    policies.kyverno.io/description: >-
      Generates default ResourceQuota when a new Namespace is created
spec:
  evaluation:
    synchronize:
      enabled: true
    generateExisting:
      enabled: true
  matchConstraints:
    resourceRules:
    - apiGroups: [""]
      apiVersions: ["v1"]
      operations: ["CREATE"]
      resources: ["namespaces"]
  variables:
    - name: nsName
      expression: "object.metadata.name"
    - name: resourceQuota
      expression: |
        {
          "kind": dyn("ResourceQuota"),
          "apiVersion": dyn("v1"),
          "metadata": dyn({
            "name": "default-resourcequota",
            "namespace": string(variables.nsName),
          }),
          "spec": dyn({
            "hard": dyn({
              "requests.cpu": "4",
              "requests.memory": "16Gi",
              "limits.cpu": "4",
              "limits.memory": "16Gi"
            })
          })
        }
  generate:
    - expression: generator.Apply(variables.nsName, [variables.resourceQuota])