apiVersion: policies.kyverno.io/v1alpha1
kind: GeneratingPolicy
metadata:
  name: add-ns-limitrange
  annotations:
    policies.kyverno.io/title: Add LimitRange
    policies.kyverno.io/category: Multi-Tenancy, EKS Best Practices
    policies.kyverno.io/subject: LimitRange
    policies.kyverno.io/minversion: 1.15.0
    policies.kyverno.io/description: >-
      Generates default LimitRange when a new Namespace is created
spec:
  evaluation:
    synchronize:
      enabled: true
    generateExisting:
      enabled: true
  matchConstraints:
    resourceRules:
    - apiGroups: [""]
      apiVersions: ["v1"]
      operations: ["CREATE"]
      resources: ["namespaces"]
  variables:
    - name: nsName
      expression: "object.metadata.name"
    - name: limitRange
      expression: |
        {
          "kind": dyn("LimitRange"),
          "apiVersion": dyn("v1"),
          "metadata": dyn({
            "name": "default-limitrange",
            "namespace": string(variables.nsName),
          }),
          "spec": dyn({
            "limits": [
              dyn({
                "type": "Container",
                "default": dyn({
                  "cpu": "500m",
                  "memory": "1Gi"
                }),
                "defaultRequest": dyn({
                  "cpu": "200m",
                  "memory": "256Mi"
                })
              })
            ]
          })
        }
  generate:
    - expression: generator.Apply(variables.nsName, [variables.limitRange])